# Generated by Django 5.2.5 on 2025-08-21 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(max_length=255, verbose_name='Backup File')),
                ('backup_size', models.BigIntegerField(verbose_name='Backup Size (bytes)')),
                ('backup_date', models.DateTimeField(auto_now_add=True, verbose_name='Backup Date')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-backup_date'],
                'indexes': [models.Index(fields=['backup_date'], name='core_backup_backup__4068e7_idx'), models.Index(fields=['status'], name='core_backup_status_57392b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('unit', models.CharField(max_length=20, verbose_name='Unit (kg, L, pcs)')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('reorder_level', models.IntegerField(verbose_name='Reorder Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='core_produc_sku_a1eae6_idx'), models.Index(fields=['category'], name='core_produc_categor_ba410e_idx'), models.Index(fields=['is_active'], name='core_produc_is_acti_1d1aa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Batch Cost Price')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Supplier')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Customer Phone')),
                ('sale_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=20, verbose_name='Sale Type')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['sale_date'], name='core_sale_sale_da_05f5fa_idx'), models.Index(fields=['customer_name'], name='core_sale_custome_6b716b_idx'), models.Index(fields=['sale_type'], name='core_sale_sale_ty_0611cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch', verbose_name='Batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Stock Addition'), ('subtraction', 'Stock Subtraction'), ('damage', 'Damaged Stock'), ('expiry', 'Expired Stock'), ('theft', 'Theft/Loss'), ('correction', 'Stock Correction')], max_length=20, verbose_name='Adjustment Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='Adjusted At')),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Adjusted By')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch', verbose_name='Batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='core_batch_expiry__7dbedc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='core_batch_batch_n_c5ed7e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjusted_at'], name='core_stocka_adjuste_8d335b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_type'], name='core_stocka_adjustm_ed5c92_idx'),
        ),
    ]
