# Generated by Django 5.2.5 on 2025-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='core_sale_custome_6b716b_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_name',
            field=models.CharField(default='Unknown Seller', max_length=200, verbose_name='Seller Name'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller_name'], name='core_sale_seller__b1622e_idx'),
        ),
    ]
