# Generated by Django 5.2.5 on 2025-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sale_core_sale_custome_6b716b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='VAT Rate (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (Excluding VAT)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total VAT Amount'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Without VAT'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='VAT Rate (%)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount (Legacy)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount (Including VAT)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price (Including VAT)'),
        ),
    ]
